"""
data_agent.py — Fabric Data Agent client (OpenAI Assistants API pattern)

Sends natural-language questions to a published Fabric Data Agent endpoint
and returns the results. The Data Agent handles SQL generation internally,
so we skip the GPT-writes-SQL pipeline entirely.

Feature-flagged via USE_DATA_AGENT env var (ADR-006, ADR-017).
When disabled, the caller falls back to GPT-writes-SQL (llm.py + db.py).

Auth: DefaultAzureCredential — Bearer token for Fabric API scope.
"""

import asyncio
import json
import logging
import os
import time
from typing import Any

from azure.identity import DefaultAzureCredential, get_bearer_token_provider
from openai import AzureOpenAI

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Config (from .env)
# ---------------------------------------------------------------------------
DATA_AGENT_URL = os.getenv("DATA_AGENT_URL", "")
DATA_AGENT_ID = os.getenv("DATA_AGENT_ID", "")
USE_DATA_AGENT = os.getenv("USE_DATA_AGENT", "false").lower() in ("true", "1", "yes")

# Fabric API scope for Azure AD token
_FABRIC_SCOPE = "https://api.fabric.microsoft.com/.default"


# ---------------------------------------------------------------------------
# Client (lazy init)
# ---------------------------------------------------------------------------
_client: AzureOpenAI | None = None


def _get_client() -> AzureOpenAI:
    """Return a cached AzureOpenAI client configured for the Fabric Data Agent."""
    global _client
    if _client is None:
        if not DATA_AGENT_URL:
            raise RuntimeError("DATA_AGENT_URL is not configured — cannot use Data Agent")

        token_provider = get_bearer_token_provider(
            DefaultAzureCredential(),
            _FABRIC_SCOPE,
        )
        _client = AzureOpenAI(
            azure_endpoint=DATA_AGENT_URL,
            azure_ad_token_provider=token_provider,
            api_version="2024-05-01-preview",
        )
        log.info("Fabric Data Agent client initialized → %s", DATA_AGENT_URL)
    return _client


# ---------------------------------------------------------------------------
# Query execution
# ---------------------------------------------------------------------------
def _query_sync(question: str, max_rows: int = 200) -> dict[str, Any]:
    """
    Send a natural-language question to the Fabric Data Agent synchronously.

    Returns:
        {
            "question": str,
            "sql": str,         # SQL generated by the Data Agent (if exposed)
            "results": [...],   # list of row dicts
            "row_count": int,
            "source": "data_agent",
        }
    """
    client = _get_client()

    if not DATA_AGENT_ID:
        raise RuntimeError("DATA_AGENT_ID is not configured — cannot use Data Agent")

    start = time.perf_counter()

    # Create a thread and run the question through the Data Agent assistant
    thread = client.beta.threads.create()
    client.beta.threads.messages.create(
        thread_id=thread.id,
        role="user",
        content=question,
    )

    run = client.beta.threads.runs.create_and_poll(
        thread_id=thread.id,
        assistant_id=DATA_AGENT_ID,
    )

    elapsed_ms = int((time.perf_counter() - start) * 1000)
    log.info("Data Agent run completed in %dms (status=%s)", elapsed_ms, run.status)

    if run.status != "completed":
        raise RuntimeError(f"Data Agent run failed: status={run.status}")

    # Retrieve the assistant's response messages
    messages = client.beta.threads.messages.list(thread_id=thread.id, order="desc")

    sql = ""
    results: list[dict[str, Any]] = []

    for msg in messages.data:
        if msg.role != "assistant":
            continue
        for block in msg.content:
            if block.type == "text":
                text = block.text.value
                # Try to parse as JSON array (Data Agent often returns structured results)
                try:
                    parsed = json.loads(text)
                    if isinstance(parsed, list):
                        results = parsed[:max_rows]
                    elif isinstance(parsed, dict):
                        # Single result or metadata envelope
                        if "results" in parsed:
                            results = parsed["results"][:max_rows]
                        elif "sql" in parsed:
                            sql = parsed.get("sql", "")
                            results = parsed.get("results", [])[:max_rows]
                        else:
                            results = [parsed]
                except (json.JSONDecodeError, TypeError):
                    # Plain text response — wrap as a single result
                    results = [{"response": text}]
        break  # Only process the first assistant message

    # Clean up the thread
    try:
        client.beta.threads.delete(thread.id)
    except Exception:
        pass  # Non-critical cleanup

    return {
        "question": question,
        "sql": sql or "(generated by Fabric Data Agent)",
        "results": results,
        "row_count": len(results),
        "source": "data_agent",
        "elapsed_ms": elapsed_ms,
    }


async def query_data_agent(question: str, max_rows: int = 200) -> dict[str, Any]:
    """
    Async wrapper — sends a question to the Fabric Data Agent.

    Returns the same dict shape as _query_sync.
    Raises RuntimeError if the Data Agent is not configured or fails.
    """
    return await asyncio.to_thread(_query_sync, question, max_rows)
